name: Dependency management
# see https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
# for more details on why and how

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    needs: build-and-update

    steps:
      - name: Auto merge (dependency updates)
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ""
          MERGE_FILTER_AUTHOR: dependabot[bot]
          MERGE_FORKS: false
          MERGE_DELETE_BRANCH: true

  build-and-update:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2
        with:
          # use a separate token to allow the push to trigger builds
          token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: "15"

      - name: Install dependencies
        run: yarn

      - name: Clean
        run: yarn clean

      - name: Fix
        run: yarn fix

      - name: Test (update snapshots)
        run: yarn test -u

      - name: Build
        run: yarn build

      - name: Add and commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          default_author: github_actions
          message: Fix lint errors and build
